language: objective-c
os: osx
osx_image: xcode7.3

before_install:
  - gem install xcpretty -N --no-ri --no-rdoc

script:
  - set -o pipefail
  - xcodebuild test -workspace SomeApp.xcworkspace -scheme SomeApp -sdk iphonesimulator9.3 -destination 'platform=iOS Simulator,name=iPhone 5s,OS=9.3' | xcpretty
